[project]
name = "dep1"
version = "0.1.0"
description = ""
authors = [
    {name = "Patrick Richter", email = "patrick-richter@posteo.de"}
]

[tool.poetry.dependencies]
python = "^3.11"
dep2 = {path = "../dep2"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
